name: flashlight

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  torch_light: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
